spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true

# Telegram Bot Configuration
telegrambot.username=TodoListDockerBot
telegrambot.token=${TELEGRAM_BOT_TOKEN:8211326121:AAE2ivQxGM1LgtztI0105s-hWF-PiOI60uo}